#!/usr/bin/env ruby
require 'date'
require 'awesome_print'
require 'dotenv'
path = File.expand_path(File.dirname(__FILE__))
e = Dotenv.load(path + "/.env")
input = "\n- " + ARGV[0]
ap e["PATH_TO_README_PARENT"]
file_path = "#{e["PATH_TO_README_PARENT"]}readme.md"
f = File.open(file_path, 'rb')
d = DateTime.now.strftime("%m/%d/%Y")
contents = f.read
if contents.include?(d)
  input = contents + input
else
  input = contents + "\n" + "## #{d}" + input
end
f = File.open(file_path, 'w')
f.write(input)
